name: Clone, Build, Sign and Release Guahao

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          # - platform: 'macos-latest' # for Intel based macs.
          #   args: '--target x86_64-apple-darwin'
          # - platform: 'windows-latest'
          #   args: ''
    
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Clone private repo
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/yuwet15/guahao-app.git
          cd guahao-app

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-src

      - name: Install dependencies
        working-directory: ./guahao-app
        run: yarn install

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Extract changelog for this version
        id: changelog
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          BODY=$(awk "/## v$VERSION/{flag=1;next}/## v/{flag=0}flag" CHANGELOG.md)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build and publish with Tauri
        uses: tauri-apps/tauri-action@v0.5.22
        with:
          projectPath: ./guahao-app
          tagName: v__VERSION__
          releaseName: "Guahao App v__VERSION__"
          releaseBody: ${{ steps.changelog.outputs.changelog }}
          includeUpdaterJson: true
          releaseDraft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_RELEASE_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
