name: Test Sign

on:
  workflow_dispatch:

jobs:  
  sign:
    runs-on: windows-latest

    steps:
      - name: Download release assets
        uses: robinraju/release-downloader@v1.10
        with:
          repository: yuwet15/guahao-app-releases
          tag: v0.1.5
          fileName: "*.exe"
          token: ${{ secrets.REPO_RELEASE_TOKEN }}

      - name: Download release assets (msi)
        uses: robinraju/release-downloader@v1.10
        with:
          repository: yuwet15/guahao-app-releases
          tag: v0.1.5
          fileName: "*.msi"
          token: ${{ secrets.REPO_RELEASE_TOKEN }}
      - name: List downloaded files
        run: |
          echo "PWD: $(Get-Location)"
          Get-ChildItem -Recurse
        shell: powershell

      - name: Decode .pfx file
        shell: bash
        run: |
          echo "${{ secrets.WINDOWS_PFX }}" | base64 -d > cert.pfx

      - name: Sign binaries with signtool
        shell: powershell
        run: |
          $files = Get-ChildItem *.exe, *.msi
          foreach ($file in $files) {
            signtool sign `
              /f cert.pfx `
              /p "${{ secrets.WINDOWS_PFX_PASS }}" `
              /tr http://timestamp.digicert.com `
              /td sha256 `
              /fd sha256 `
              "$($file.FullName)"
          }
      - name: Show current directory and files
        run: |
          echo "PWD: $(Get-Location)"
          Get-ChildItem -Recurse
        shell: powershell

      - name: Upload signed assets (replace)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1.5
          files: |
            **/*.exe
            **/*.msi
          token: ${{ secrets.REPO_RELEASE_TOKEN }}
