name: Test Sign

on:
  workflow_dispatch:

jobs:  
  sign:
    runs-on: windows-latest

    steps:
      - name: Download release assets
        uses: robinraju/release-downloader@v1.10
        with:
          repository: yuwet15/guahao-app-releases
          tag: v0.1.5
          fileName: "*.exe"
          token: ${{ secrets.REPO_RELEASE_TOKEN }}

      - name: Download release assets (msi)
        uses: robinraju/release-downloader@v1.10
        with:
          repository: yuwet15/guahao-app-releases
          tag: v0.1.5
          fileName: "*.msi"
          token: ${{ secrets.REPO_RELEASE_TOKEN }}
      
      - name: List downloaded files
        run: |
          echo "PWD: $(Get-Location)"
          Get-ChildItem -Recurse
        shell: powershell
      
      - name: Find MSI and EXE files
        id: find_files
        run: |
          $paths = Get-ChildItem -Recurse -Include *.msi, *.exe | ForEach-Object { $_.FullName }
          $joined = $paths -join "`n"
          "files=$joined" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8

      - name: Sign all binaries
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: ${{ secrets.WINDOWS_PFX }}
          password: ${{ secrets.WINDOWS_PFX_PASS }}
          files: ${{ steps.find_files.outputs.files }}

      - name: Show current directory and files
        run: |
          echo "PWD: $(Get-Location)"
          Get-ChildItem -Recurse
        shell: powershell

      - name: Upload signed assets (replace)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1.5
          files: |
            **/*.exe
            **/*.msi
          token: ${{ secrets.REPO_RELEASE_TOKEN }}
